# Generated by Django 5.0.7 on 2024-07-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
                ('subcategory_name', models.CharField(max_length=64)),
                ('subsubcategory', models.CharField(max_length=64)),
                ('details', models.JSONField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
