# Generated by Django 5.0.7 on 2024-07-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circuitrecommender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourism',
            name='details',
        ),
        migrations.AddField(
            model_name='tourism',
            name='DietaryRestrictions',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='tourism',
            name='Dishes',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='tourism',
            name='Duration',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='tourism',
            name='GoodFor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourism',
            name='Meals',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourism',
            name='cuisine',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourism',
            name='price',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
