# Generated by Django 5.0.7 on 2024-07-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Circuitrecommender', '0002_remove_tourism_details_tourism_dietaryrestrictions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourism',
            old_name='DietaryRestrictions',
            new_name='Dietaryrestrictions',
        ),
    ]
