# Generated by Django 5.0.7 on 2024-07-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circuitrecommender', '0004_tourism_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourism',
            name='Meals',
        ),
        migrations.AddField(
            model_name='tourism',
            name='destinations_features',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
