# Generated by Django 5.0.7 on 2024-07-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Circuitrecommender', '0005_remove_tourism_meals_tourism_destinations_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourism',
            name='Dishes',
        ),
    ]
