# Generated by Django 5.0.6 on 2024-07-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circuitrecommender', '0006_remove_tourism_dishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('hotelClass', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('priceLevel', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('subcategories', models.JSONField()),
                ('website', models.URLField()),
                ('amenities', models.TextField()),
            ],
        ),
    ]
